// Generated file, do not edit.
// version: 0.1.0

const std = @import("std");
const sf = @import("sf_bindings.zig");

const HandleTypes = struct {
    Instance: type,
    Surface: type,
    Adapter: type,
    Device: type,
    Queue: type,
    Semaphore: type,
    Swapchain: type,
    CommandBuffer: type,
    Texture: type,
    Pipeline: type,
};

fn Functions(handle_types: HandleTypes) type {
    return struct {
        createSurfaceWin32: *const fn (device: *handle_types.Device, desc: sf.SurfaceWin32Desc) callconv(sf.@"callconv") *handle_types.Surface,
        createSurfaceXlib: *const fn (device: *handle_types.Device, desc: sf.SurfaceXlibDesc) callconv(sf.@"callconv") *handle_types.Surface,
        destroySurface: *const fn (surface: *handle_types.Surface) callconv(sf.@"callconv") void,
        surfaceSupportedUsage: *const fn (device: *handle_types.Device, surface: *handle_types.Surface) callconv(sf.@"callconv") sf.TextureUsage,
        surfaceFormats: *const fn (device: *handle_types.Device, surface: *handle_types.Surface, formats_capacity: usize, formats: ?[*]sf.Format, format_count: *usize) callconv(sf.@"callconv") void,
        surfacePresentModes: *const fn (device: *handle_types.Device, surface: *handle_types.Surface, present_modes_capacity: usize, present_modes: ?[*]sf.PresentMode, present_mode_count: *usize) callconv(sf.@"callconv") void,
        deviceToHostPointer: *const fn (device: *handle_types.Device, address: sf.DeviceAddress) callconv(sf.@"callconv") *anyopaque,
        malloc: *const fn (device: *handle_types.Device, size: usize, alignment: usize, memory: sf.Memory) callconv(sf.@"callconv") sf.DeviceAddress,
        free: *const fn (device: *handle_types.Device, address: sf.DeviceAddress) callconv(sf.@"callconv") void,
        descriptorSizeAndHeapAlign: *const fn (device: *handle_types.Device) callconv(sf.@"callconv") sf.SizeAndAlign,
        storeDescriptor: *const fn (device: *handle_types.Device, descriptor: *const sf.Descriptor, heap: [*]u8, index: usize) callconv(sf.@"callconv") void,
        createQueue: *const fn (device: *handle_types.Device, queue_type: sf.QueueType) callconv(sf.@"callconv") *handle_types.Queue,
        startCommandRecording: *const fn (queue: *handle_types.Queue) callconv(sf.@"callconv") *handle_types.CommandBuffer,
        submit: *const fn (queue: *handle_types.Queue, command_buffer_count: usize, command_buffers: [*]const *handle_types.CommandBuffer) callconv(sf.@"callconv") void,
        submitAndSignal: *const fn (queue: *handle_types.Queue, command_buffer_count: usize, command_buffers: [*]const *handle_types.CommandBuffer, signal_semaphore: *handle_types.Semaphore, signal_value: u64) callconv(sf.@"callconv") void,
        createSemaphore: *const fn (device: *handle_types.Device, initial_value: u64) callconv(sf.@"callconv") *handle_types.Semaphore,
        destroySemaphore: *const fn (semaphore: *handle_types.Semaphore) callconv(sf.@"callconv") void,
        waitSemaphore: *const fn (semaphore: *handle_types.Semaphore, value: u64) callconv(sf.@"callconv") void,
        createSwapchain: *const fn (queue: *handle_types.Queue, surface: *handle_types.Surface, desc: sf.SwapchainDesc) callconv(sf.@"callconv") *handle_types.Swapchain,
        destroySwapchain: *const fn (swapchain: *handle_types.Swapchain) callconv(sf.@"callconv") void,
        swapchainAcquireNextTexture: *const fn (swapchain: *handle_types.Swapchain, queue: *handle_types.Queue, width: u32, height: u32) callconv(sf.@"callconv") *handle_types.Texture,
        swapchainPresent: *const fn (swapchain: *handle_types.Swapchain, queue: *handle_types.Queue, semaphore: *handle_types.Semaphore, semaphore_value: u64) callconv(sf.@"callconv") void,
        setActiveTextureHeap: *const fn (command_buffer: *handle_types.CommandBuffer, heap_address: sf.DeviceAddress) callconv(sf.@"callconv") void,
        setPipeline: *const fn (command_buffer: *handle_types.CommandBuffer, pipeline: *handle_types.Pipeline) callconv(sf.@"callconv") void,
        dispatch: *const fn (command_buffer: *handle_types.CommandBuffer, data: sf.DeviceAddress, x: u32, y: u32, z: u32) callconv(sf.@"callconv") void,
        barrier: *const fn (command_buffer: *handle_types.CommandBuffer, before: sf.Stage, after: sf.Stage, hazard: sf.Hazard) callconv(sf.@"callconv") void,
        copyTextureToBuffer: *const fn (command_buffer: *handle_types.CommandBuffer, source: sf.DeviceAddress, destination: sf.DeviceAddress, texture: *handle_types.Texture) callconv(sf.@"callconv") void,
        copyBufferToTexture: *const fn (command_buffer: *handle_types.CommandBuffer, source: sf.DeviceAddress, destination: sf.DeviceAddress, texture: *handle_types.Texture) callconv(sf.@"callconv") void,
        beginRenderPass: *const fn (command_buffer: *handle_types.CommandBuffer, desc: sf.RenderPassDesc) callconv(sf.@"callconv") void,
        endRenderPass: *const fn (command_buffer: *handle_types.CommandBuffer) callconv(sf.@"callconv") void,
        draw: *const fn (command_buffer: *handle_types.CommandBuffer, vertex_data: sf.DeviceAddress, pixel_data: sf.DeviceAddress, vertex_count: u32, instance_count: u32) callconv(sf.@"callconv") void,
        drawIndexed: *const fn (command_buffer: *handle_types.CommandBuffer, vertex_data: sf.DeviceAddress, pixel_data: sf.DeviceAddress, index_type: sf.IndexType, indices: sf.DeviceAddress, index_count: u32) callconv(sf.@"callconv") void,
        drawIndexedInstanced: *const fn (command_buffer: *handle_types.CommandBuffer, vertex_data: sf.DeviceAddress, pixel_data: sf.DeviceAddress, index_type: sf.IndexType, indices: sf.DeviceAddress, index_count: u32, instance_count: u32) callconv(sf.@"callconv") void,
        drawIndexedInstancedIndirect: *const fn (command_buffer: *handle_types.CommandBuffer, vertex_data: sf.DeviceAddress, pixel_data: sf.DeviceAddress, index_type: sf.IndexType, indices: sf.DeviceAddress, arguments: sf.DeviceAddress) callconv(sf.@"callconv") void,
        textureSizeAndAlign: *const fn (device: *handle_types.Device, desc: sf.TextureDesc) callconv(sf.@"callconv") sf.SizeAndAlign,
        createTexture: *const fn (device: *handle_types.Device, desc: sf.TextureDesc, data: sf.DeviceAddress) callconv(sf.@"callconv") *handle_types.Texture,
        destroyTexture: *const fn (texture: *handle_types.Texture) callconv(sf.@"callconv") void,
        textureStorageDescriptor: *const fn (texture: *handle_types.Texture, desc: sf.TextureViewDesc) callconv(sf.@"callconv") sf.Descriptor,
        textureViewDescriptor: *const fn (texture: *handle_types.Texture, desc: sf.TextureViewDesc) callconv(sf.@"callconv") sf.Descriptor,
        createComputePipeline: *const fn (device: *handle_types.Device, ir_size: usize, ir: [*]const u8) callconv(sf.@"callconv") *handle_types.Pipeline,
        createGraphicsPipeline: *const fn (device: *handle_types.Device, vertex_ir_size: usize, vertex_ir: [*]const u8, pixel_ir_size: usize, pixel_ir: [*]const u8, desc: sf.GraphicsPipelineDesc) callconv(sf.@"callconv") *handle_types.Pipeline,
        destroyPipeline: *const fn (pipeline: *handle_types.Pipeline) callconv(sf.@"callconv") void,
    };
}

pub fn map(
    comptime handle_types: HandleTypes,
    comptime functions: Functions(handle_types),
) std.StaticStringMap(*const anyopaque) {
    return .initComptime(@as([]const struct { []const u8, *const anyopaque }, &.{
        .{ "sfCreateSurfaceWin32", @ptrCast(functions.createSurfaceWin32) },
        .{ "sfCreateSurfaceXlib", @ptrCast(functions.createSurfaceXlib) },
        .{ "sfDestroySurface", @ptrCast(functions.destroySurface) },
        .{ "sfSurfaceSupportedUsage", @ptrCast(functions.surfaceSupportedUsage) },
        .{ "sfSurfaceFormats", @ptrCast(functions.surfaceFormats) },
        .{ "sfSurfacePresentModes", @ptrCast(functions.surfacePresentModes) },
        .{ "sfDeviceToHostPointer", @ptrCast(functions.deviceToHostPointer) },
        .{ "sfMalloc", @ptrCast(functions.malloc) },
        .{ "sfFree", @ptrCast(functions.free) },
        .{ "sfDescriptorSizeAndHeapAlign", @ptrCast(functions.descriptorSizeAndHeapAlign) },
        .{ "sfStoreDescriptor", @ptrCast(functions.storeDescriptor) },
        .{ "sfCreateQueue", @ptrCast(functions.createQueue) },
        .{ "sfStartCommandRecording", @ptrCast(functions.startCommandRecording) },
        .{ "sfSubmit", @ptrCast(functions.submit) },
        .{ "sfSubmitAndSignal", @ptrCast(functions.submitAndSignal) },
        .{ "sfCreateSemaphore", @ptrCast(functions.createSemaphore) },
        .{ "sfDestroySemaphore", @ptrCast(functions.destroySemaphore) },
        .{ "sfWaitSemaphore", @ptrCast(functions.waitSemaphore) },
        .{ "sfCreateSwapchain", @ptrCast(functions.createSwapchain) },
        .{ "sfDestroySwapchain", @ptrCast(functions.destroySwapchain) },
        .{ "sfSwapchainAcquireNextTexture", @ptrCast(functions.swapchainAcquireNextTexture) },
        .{ "sfSwapchainPresent", @ptrCast(functions.swapchainPresent) },
        .{ "sfSetActiveTextureHeap", @ptrCast(functions.setActiveTextureHeap) },
        .{ "sfSetPipeline", @ptrCast(functions.setPipeline) },
        .{ "sfDispatch", @ptrCast(functions.dispatch) },
        .{ "sfBarrier", @ptrCast(functions.barrier) },
        .{ "sfCopyTextureToBuffer", @ptrCast(functions.copyTextureToBuffer) },
        .{ "sfCopyBufferToTexture", @ptrCast(functions.copyBufferToTexture) },
        .{ "sfBeginRenderPass", @ptrCast(functions.beginRenderPass) },
        .{ "sfEndRenderPass", @ptrCast(functions.endRenderPass) },
        .{ "sfDraw", @ptrCast(functions.draw) },
        .{ "sfDrawIndexed", @ptrCast(functions.drawIndexed) },
        .{ "sfDrawIndexedInstanced", @ptrCast(functions.drawIndexedInstanced) },
        .{ "sfDrawIndexedInstancedIndirect", @ptrCast(functions.drawIndexedInstancedIndirect) },
        .{ "sfTextureSizeAndAlign", @ptrCast(functions.textureSizeAndAlign) },
        .{ "sfCreateTexture", @ptrCast(functions.createTexture) },
        .{ "sfDestroyTexture", @ptrCast(functions.destroyTexture) },
        .{ "sfTextureStorageDescriptor", @ptrCast(functions.textureStorageDescriptor) },
        .{ "sfTextureViewDescriptor", @ptrCast(functions.textureViewDescriptor) },
        .{ "sfCreateComputePipeline", @ptrCast(functions.createComputePipeline) },
        .{ "sfCreateGraphicsPipeline", @ptrCast(functions.createGraphicsPipeline) },
        .{ "sfDestroyPipeline", @ptrCast(functions.destroyPipeline) },
    }));
}
